import React from 'react';
import { Metadata } from 'next';
import Link from 'next/link';
import { ChevronRight, Home } from 'lucide-react';
import ConflictResolverClient from '@/components/ai-conflict-resolver/ConflictResolverClient';

export const metadata: Metadata = {
  title: "AI Conflict Resolver",
  description: "Craft calm, mature, and de-escalating text messages to resolve conflicts with partners or bosses.",
  alternates: {
    canonical: 'https://quicktool.space/tools/ai-conflict-resolver'
  },
  openGraph: { title: 'AI Conflict Resolver - QuickTools.ai', description: 'Prepare calm, constructive conflict-resolution messages.', url: 'https://quicktool.space/tools/ai-conflict-resolver', type: 'website', images: [{ url: 'https://quicktool.space/api/og?title=AI%20Conflict%20Resolver&type=tool', width: 1200, height: 630, alt: 'AI Conflict Resolver' }] },
  twitter: { card: 'summary_large_image', title: 'AI Conflict Resolver - QuickTools.ai', description: 'Prepare calm, constructive conflict-resolution messages.', images: ['https://quicktool.space/api/og?title=AI%20Conflict%20Resolver&type=tool'] }
};

export default function Page() {
  return (
    <div className="flex-grow bg-[#F8FAFC] flex flex-col font-sans relative">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify([
      {
        "@context": "https://schema.org",
        "@type": "WebPage",
        "name": "AI Conflict Resolver",
        "description": "Craft calm, mature, and de-escalating text messages to resolve conflicts with partners or bosses.",
        "url": "https://quicktool.space/tools/ai-conflict-resolver"
      },
      {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
          { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://quicktool.space" },
          { "@type": "ListItem", "position": 2, "name": "Tools", "item": "https://quicktool.space/tools" },
          { "@type": "ListItem", "position": 3, "name": "Productivity", "item": "https://quicktool.space/tools/category/career-hr" },
          { "@type": "ListItem", "position": 4, "name": "AI Conflict Resolver", "item": "https://quicktool.space/tools/ai-conflict-resolver" }
        ]
      }
    ]) }} />
      
      <div className="max-w-[1440px] w-full mx-auto px-4 sm:px-6 lg:px-8 pb-8 pt-[15px] flex-grow flex flex-col relative z-10">
        <div className="flex items-center mb-[25px]">
          <nav className="flex items-center space-x-2 text-sm font-medium text-[#6B7280]">
            <Link href="/" className="hover:text-[#111827] transition-colors flex items-center gap-1.5">
              <Home className="w-4 h-4" /> Home
            </Link>
            <ChevronRight className="w-4 h-4 text-gray-400" />
            <Link href="/tools" className="hover:text-[#111827] transition-colors">
              All Tools
            </Link>
            <ChevronRight className="w-4 h-4 text-gray-400" />
            <span className="text-[#F59E0B] font-bold">AI Conflict Resolver</span>
          </nav>
        </div>
        <div className="flex-1 w-full max-w-[1600px] mx-auto py-2 h-[calc(100vh-80px)]">
          <ConflictResolverClient />
        </div>
      
        {/* Visible FAQ Section for SEO and Users */}
        <div id="faq" className="mt-16 bg-white rounded-2xl shadow-sm border border-slate-200 p-8">
          <h2 className="text-2xl font-bold text-slate-900 mb-6">Frequently Asked Questions</h2>
          <div className="space-y-6">
            <div>
              <h3 className="text-lg font-semibold text-slate-800">What is AI Conflict Resolver?</h3>
              <p className="text-slate-600 mt-2">The AI Conflict Resolver is an AI-assisted tool by QuickTools designed to help you craft calm, mature, and de-escalating text messages to resolve conflicts with partners or bosses.</p>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-slate-800">How does the AI Conflict Resolver work?</h3>
              <p className="text-slate-600 mt-2">It uses AI-assisted processing to analyze your input and automatically generate structured results from the details you provide. Just provide a prompt, and the AI handles the rest.</p>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-slate-800">Can I use AI Conflict Resolver for professional purposes?</h3>
              <p className="text-slate-600 mt-2">Yes, the output generated by our AI is designed to be highly professional and can be directly used for business applications, marketing, and client work.</p>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-slate-800">Is it fast to generate results?</h3>
              <p className="text-slate-600 mt-2">Generation time depends on the request and current service availability. Review the result before using it.</p>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-slate-800">Do I need to download any software?</h3>
              <p className="text-slate-600 mt-2">No, the AI Conflict Resolver is entirely web-based and runs in your browser. You can access it from any device with an internet connection.</p>
            </div>
            <div>
              <h3 className="text-lg font-semibold text-slate-800">Is the AI Conflict Resolver free to use?</h3>
              <p className="text-slate-600 mt-2">QuickTools offers limited free access and paid plans. Current limits are shown on the pricing page.</p>
            </div>
          </div>
        </div>

</div>
    </div>
  );
}
