
import React from 'react';
import { allTools } from '@/lib/toolsRegistry';
import {
  Search,
  Zap,
  Image as ImageIcon,
  PenTool,
  Code,
  Video,
  ArrowRight,
  LayoutGrid,
  Moon,
  MessageCircle,
  Palette,
  Briefcase,
  TrendingUp,
  Crown,
  Flame,
  Sparkles,
  Star,
  Clock,
  ChevronDown,
  Globe,
  Share2,
  Mail,
  Home,
  ChevronRight,
  LucideIcon,
  Menu,
  X,
  FileText,
  Languages,
  FileUser,
  Link2,
  Gift,
  SpellCheck,
  QrCode,
  Hash,
  Lightbulb,
  List,
  RefreshCw,
  ShoppingBag,
  Magnet,
  Megaphone,
  Key,
  Code2,
  Terminal,
  Braces,
  Type,
  Utensils,
  Dumbbell,
  QuoteIcon,
  Users,
  Database,
  Mic2,
  BookOpen,
  Map,
  CalendarDays,
  Calendar,
  PlaySquare,
  Wind,
  GitBranch,
  FileX,
  SmilePlus,
  CloudSun,
  MessageSquare,
  Home as HomeIcon,
  GraduationCap,
  Presentation,
  Scale,
  Target,
  BarChart2,
  UserCircle,
  PhoneCall,
  Shield,
  Mic,
  Film,
  MailOpen,
  Layout,
  ShoppingCart,
  Rocket,
  DollarSign,
  Grid,
  AlertTriangle,
  Leaf,
  UserPlus,
  Book,
  Heart,
  CheckSquare,
  LifeBuoy,
  Send,
  Award,
  FileCheck,
  Handshake,
  Settings,
  Volume2
} from 'lucide-react';

// âœ… Static icon map â€” RSC bundler idi safely handle cheyagaladu
export const IconMap: Record<string, LucideIcon> = {
  LayoutGrid,
  ImageIcon,
  PenTool,
  Video,
  Code,
  MessageCircle,
  Palette,
  Briefcase,
  Search,
  TrendingUp,
  Flame,
  Sparkles,
  Star,
  Clock,
  FileText,
  Languages,
  FileUser,
  Link2,
  Gift,
  SpellCheck,
  QrCode,
  Hash,
  Mail,
  Lightbulb,
  List,
  RefreshCw,
  ShoppingBag,
  Magnet,
  Megaphone,
  Key,
  Code2,
  Terminal,
  Braces,
  Type,
  Utensils,
  Dumbbell,
  QuoteIcon,
  Users,
  Database,
  Mic2,
  BookOpen,
  Map,
  CalendarDays,
  Calendar,
  PlaySquare,
  Wind,
  GitBranch,
  FileX,
  SmilePlus,
  CloudSun,
  MessageSquare,
  Home: HomeIcon,
  GraduationCap,
  Presentation,
  Scale,
  Target,
  BarChart2,
  UserCircle,
  PhoneCall,
  Shield,
  Mic,
  Film,
  MailOpen,
  Layout,
  ShoppingCart,
  Rocket,
  DollarSign,
  Grid,
  AlertTriangle,
  Leaf,
  UserPlus,
  Book,
  Heart,
  CheckSquare,
  LifeBuoy,
  Send,
  Award,
  FileCheck,
  Handshake,
  Settings,
  Volume2
};

function DynamicIcon({ name, className }: { name: string; className?: string }) {
  const Icon = IconMap[name];
  if (!Icon) return null;
  return React.createElement(Icon, { className });
}

export const categoriesList = [
  { name: 'All Tools', iconName: 'LayoutGrid' },
  { name: 'AI Image', iconName: 'ImageIcon' },
  { name: 'AI Writer', iconName: 'PenTool' },
  { name: 'AI Video', iconName: 'Video' },
  { name: 'AI Code', iconName: 'Code' },
  { name: 'AI Chat', iconName: 'MessageCircle' },
  { name: 'Design', iconName: 'Palette' },
  { name: 'Productivity', iconName: 'Briefcase' },
  { name: 'Utilities', iconName: 'Link2' },
  { name: 'SEO', iconName: 'Search' },
  { name: 'Business', iconName: 'TrendingUp' },
  { name: 'Marketing', iconName: 'Megaphone' },
  { name: 'Sales', iconName: 'DollarSign' },
  { name: 'HR', iconName: 'Users' },
  { name: 'Media', iconName: 'Mic' },
  { name: 'Education', iconName: 'GraduationCap' },
  { name: 'Lifestyle', iconName: 'Heart' },
];


const filtersList = [
  { name: 'Popular', iconName: 'Flame' },
  { name: 'New', iconName: 'LayoutGrid' },
  { name: 'Free', iconName: 'Gift' },
  { name: 'Trending', iconName: 'TrendingUp' },
  { name: 'Most Used', iconName: 'Star' },
  { name: 'Recent', iconName: 'Clock' },
];

export function isNewTool(createdAt?: string) {
  if (!createdAt) return false;
  const launchDate = new Date(createdAt);
  const now = new Date();
  const diffDays = Math.floor((now.getTime() - launchDate.getTime()) / (1000 * 3600 * 24));
  return diffDays <= 30;
}

export { allTools };
