import { Metadata } from 'next';
import AiMarketingPlanClient from '@/components/ai-marketing-plan/AiMarketingPlanClient';
import { Sparkles, ChevronRight, Home } from 'lucide-react';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'AI Marketing Plan Generator | Premium Tools',
  description: 'Generate a comprehensive marketing plan and strategy.',
    keywords: ["AI Marketing Plan","Marketing Plan AI","Free AI Marketing Plan","Best AI Marketing Plan","Online Marketing Plan","AI Marketing Plan Tool","QuickTools AI"],
    alternates: { canonical: 'https://quicktool.space/tools/ai-marketing-plan' },
    openGraph: {
            title: "AI Marketing Plan Generator | Premium Tools",
            description: "Generate a comprehensive marketing plan and strategy.",
            url: 'https://quicktool.space/tools/ai-marketing-plan',
            siteName: 'QuickTools.ai',
            type: 'website',
            images: [{ url: `https://quicktool.space/api/og?title=${encodeURIComponent("QuickTools AI Tool")}&type=tool`, width: 1200, height: 630, alt: `QuickTools AI Tool - QuickTools.ai` }]
          },
    twitter: {
            card: 'summary_large_image',
            title: "AI Marketing Plan Generator | Premium Tools",
            description: "Generate a comprehensive marketing plan and strategy.",
            images: [`https://quicktool.space/api/og?title=${encodeURIComponent("QuickTools AI Tool")}&type=tool`]
          }
};

export default function Page() {
  return (
    <div className="flex-1 w-full max-w-[1600px] mx-auto px-4 md:px-6 lg:px-8 py-6 h-[calc(100vh-80px)]">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify([
      {
            "@context": "https://schema.org",
            "@type": "SoftwareApplication",
            "name": "AI Marketing Plan Generator",
            "applicationCategory": "BusinessApplication",
            "operatingSystem": "Any",
            "description": "Generate a comprehensive marketing plan and strategy.",
            "offers": {
              "@type": "Offer",
              "price": "0",
              "priceCurrency": "USD"
            }
          , "featureList": "AI-powered, fast generation, free to use, no signup required for basic use"},
      {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
          { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://quicktool.space" },
          { "@type": "ListItem", "position": 2, "name": "Tools", "item": "https://quicktool.space/tools" },
          { "@type": "ListItem", "position": 3, "name": "Marketing", "item": "https://quicktool.space/tools?category=marketing" },
          { "@type": "ListItem", "position": 4, "name": "QuickTools AI Tool", "item": "https://quicktool.space/tools/ai-marketing-plan" }
        ]
      },
      {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
          { "@type": "Question", "name": "What is QuickTools AI Tool?", "acceptedAnswer": { "@type": "Answer", "text": "The QuickTools AI Tool is an advanced AI-powered tool by QuickTools designed to help you generate a comprehensive marketing plan and strategy." } },
          { "@type": "Question", "name": "Will this help my SEO rankings?", "acceptedAnswer": { "@type": "Answer", "text": "Yes, the content generated is optimized for search engines, helping you target the right keywords and improve your organic visibility." } },
          { "@type": "Question", "name": "Can I use QuickTools AI Tool for professional purposes?", "acceptedAnswer": { "@type": "Answer", "text": "Yes, the output generated by our AI is designed to be highly professional and can be directly used for business applications, marketing, and client work." } },
          { "@type": "Question", "name": "Is it fast to generate results?", "acceptedAnswer": { "@type": "Answer", "text": "Absolutely. It usually takes just 2-3 seconds to generate the desired output, making it one of the fastest tools available." } },
          { "@type": "Question", "name": "Do I need to download any software?", "acceptedAnswer": { "@type": "Answer", "text": "No, the QuickTools AI Tool is entirely web-based and runs in your browser. You can access it from any device with an internet connection." } },
          { "@type": "Question", "name": "Is the QuickTools AI Tool free to use?", "acceptedAnswer": { "@type": "Answer", "text": "Yes, you can use the QuickTools AI Tool and many other tools on QuickTools.ai for free without needing a credit card." } }
        ]
      }
    ]) }}
      />
      
      {/* Breadcrumbs */}
      <nav className="flex items-center gap-2 text-sm text-[#6B7280] mb-6 animate-in fade-in slide-in-from-left-4 duration-500">
        <Link href="/" className="hover:text-[#111827] transition-colors flex items-center gap-1.5"><Home className="w-4 h-4" /> Home</Link>
        <ChevronRight className="w-4 h-4" />
        <Link href="/tools" className="hover:text-[#111827] transition-colors">All Tools</Link>
        <ChevronRight className="w-4 h-4" />
        <span className="text-[#111827] font-semibold flex items-center gap-1.5"><Sparkles className="w-4 h-4 text-[#F59E0B]" /> Marketing Plan Generator</span>
      </nav>

      <AiMarketingPlanClient />
    </div>
  );
}
